# Generated by Django 2.1.2 on 2018-10-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20181019_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='job',
        ),
    ]
