# Generated by Django 2.1.2 on 2018-10-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
