# Generated by Django 2.1.2 on 2018-10-22 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(upload_to='static/img/uploads/'),
        ),
    ]
